# Generated by Django 3.1 on 2022-03-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_food', models.CharField(max_length=200)),
                ('toys', models.CharField(max_length=100)),
                ('sunbed', models.CharField(max_length=100)),
                ('clothes', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cat')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dog_food', models.CharField(max_length=200)),
                ('collar', models.CharField(max_length=150)),
                ('toys', models.CharField(max_length=100)),
                ('sunbed', models.CharField(max_length=200)),
                ('clothes', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='dog')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
